DISCORD:
  SERVER_ID: ""
  CHAT_CHANNEL_ID: ""
  AVATAR_SERVICE_URL: ""
  BOT_TOKEN: ""
  WEBHOOK_URL: ""
DATABASE:
  USERNAME: ""
  PASSWORD: ""
  ADDRESS: ""
  DATABASE: ""
  RECREATE: false
DEATH_MESSAGES:

